### ISSUE TITLE
add removal of whole object

### ISSUE THREAD

**Issue by juliangruber** [juliangruber/level-object#2]
could be

- `obj.del('object-name')` to delete the whole object
- `obj.del('object-name', 'key')` to delete a k/v pair

Important: use `arguments.length` check instead of `if (key)` so a falsy or undefined key wouldn't cause the object to be deleted by accident

**Comment by deanlandolt** [comment]
If something like `obj.get('object-name', [ 'foo', 'bar', 'baz' ])` was like a "projection" of the entire set of attributes associated w/ `'object-name'`, perhaps the entire set could be retrieved w/ a sigil representing some kind of query, like `obj.get('object-name', '*')`. And `obj.del('object-name', ['key'])` would make sense as an API for deleting a specific key and would be unambiguous with an API for deleting an entire object, i.e. `obj.del('object-name', '*')`...

The idea being that you can either explicitly state the set of attributes or have some API to reference a range them (including the entire range). This may be too higher-level for `level-object`, and could be modeled on top -- I only suggest it because it may help w/ the possible ambiguity you mention above.

**Comment by juliangruber** [comment]
https://github.com/juliangruber/level-object/commit/8ee468bba8b39963d2814ab666763bf78941b4f4
